### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"test1@test1.com",
  "password": "123456"
}

### signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"test1@test1.com",
  "password": "123456"
}

### Get the currently signed user
GET http://localhost:3000/auth/whoami

### signout user
POST http://localhost:3000/auth/signout



###find user by user id
GET http://localhost:3000/auth/d991450c-44cc-4b64-9d48-862b193e516b
Content-Type: application/json


###find all users with email test1@gmail.com
GET http://localhost:3000/auth/?email=taaaaaaa@gmail.com
Content-Type: application/json

###Delete user by Id
DELETE http://localhost:3000/auth/61cf0875310889763cf16686
Content-Type: application/json

###Update user by Id
PATCH http://localhost:3000/auth/61cf091fc5280a7975a6c096
Content-Type: application/json

{
  "email":"taaaaaaa@gmail.com",
  "password": "tretertertretertetret",
  "id":"61cf091fc5280a7975a6c09b"
}


###Set a color
Get http://localhost:3000/auth/colors/dasdsdadsadasdsss

###get the color
Get http://localhost:3000/auth/colors

